1	Unknown algorithm
1101	Module is inside the algorithm
1102	Embedded module
1103	Embedded description of the algorithm
1104	Line is out of the algorithm
1105	Line is out of the algorithm
1106	No algorithm descriprion
1107	"begin" is in the wrong place
1108	Strange "then"
1109	"then" is in the wrong place
1110	Strange "if" 
1111	"else" is in the wrong place
1112	Srange "at"
1113	"at" is in the wrong place
1114	Strange "pre"
1115	"pre" is in the wrong place
1116	Strange "post"
1117	"post"  is in the wrong place
1118	Strange "assert"
1119	"assert"  is in the wrong place
1120	No "begin" for "end"
1121	"end"  is in the wrong place
1122	No "do"  for "end_do"
1123	"do" is in the wrong place
1124	Strange "end_if"
1125	"end_if" is in the wrong place
1126	No "end_module" for "module"
1127	"end_module" is in the wrong place
1128	Line is out of the algorithm
1129	No algorithm implementation
1130	No "end"
1131	No "end_do"  for "do"
1132	No "end_if" after "else"
1133	No "then" after "if"
1134	No "end_if" after "then"
1135	"select" without "at"
1136	 No "end_if" after "at"
1137	 No algorithm implementation after "assert"
1138	 No algorithm implementation after "pre"
1139	 No algorithm implementation after "post"
1140	No module for "end_module" 
1141	No "end"
1142	 "end_module"  is before end
1143	"end_module"  is before "end_do"
1144	"end_module"  is before the algorithm implementation
1145	"end_module"  is before "end_if"
1146	"end_module"  is before "end_if"
1147	"end_module"  is before "end_if"
1148	"end_module"  is before "end_if"
1149	 "end_module"  is before  "then"
1150	"end_module"  is before the algorithm implementation
1151	"end_module"  is before the algorithm implementation
1152	"end_module"  is before the algorithm implementation
1153	"end" instead of "end_do"
1154	"end"  is before the algorithm implementation
1155	"end"  is before "end_if"
1156	"end"  is before "end_if"
1157	"end"  is before "end_if"
1158	"end"  is before "end_if"
1159	"end"  is before then
1160	"end"  is before the algorithm implementation
1161	"end"  is before the algorithm implementation
1162	"end"  is before the algorithm implementation
1163	"end" _module instead of "end" 
1164	No "do"  for "end_do"
1165	No "do"  for "end_do"
1166	No "do"  for "end_do"
1167	No "do"  for "end_do"
1168	No "do"  for "end_do"
1169	No "do"  for "end_do"
1170	No "do"  for "end_do"
1171	No "do"  for "end_do"
1172	No "do"  for "end_do"
1173	No "do"  for "end_do"
1174	"end_do"  instead of "end_module" 
1175	Strange "end_if"
1176	Strange "end_if"
1177	Strange "end_if"
1179	"end_if" is before at
1180	No then between if and "end_if"
1181	"end_if" is before the algorithm implementation
1182	"end_if" is before the algorithm implementation
1183	"end_if" is before the algorithm implementation
1184	"end_if" instead of "end_module" 
1185	Line is out of algorithms
1186	No "do" for "od_at"
1187	"od_at"  is before "end_module" 
1188	"end_do" without "do"
1189	"od_at"  is before alg implementation
1190	"od_at" instead of "end_if"
1191	"od_at" instead of "end_if"
1192	"od_at" instead of "end_if"
1193	"od_at" instead of "end_if"
1194	"od_at" instead of "end_if"
1195	"od_at"  is before alg implementation
1196	"od_at"  is before alg implementation
1197	"od_at"  is before alg implementation
1198	"od_at" is in the wrong place
1199	Info comment out of alg
1202	To many :=
1203	Line is out of algorithms
1211	 No name for module
1212	Garbage after "end"
1214	No such module
1216	Load module error
1217	Wrong usage
1218	module is already loaded
1219	Too many modules in the "end_if"les
1220	Name conflict
1301	excess :
1302	The variable is already declared
1303	Where are the names?
1304	No  [ ] here 
1305	The name is the module's name
1306	The name is the algorithm's name
1307	The variable is desribed in the module
1308	 No name of variable
1309	Extra comma 
1310	Error: description inside the loop
2101	Too much names in the program
2102	Two [[
2103	 ] before [
2104	 No [
2105	 No ]
2106	Wrong pair [..]
2107	Garbage after ]
2108	Dimension > 3
2109	No : (colon)
2110	Bad boundary
2111	Bad boundary
2112	unpaired "
2201	 wrong number of brackets
2202	Wrong brackets
2203	Garbage at the end of line
2204	Unpaired [
2205	Unpaired ]  
2206	No algorithm name
2207	Function cannot return array
2208	 No algorithm name
2209	Double description of the algorithm
2210	Wrong name
2211	No arg - do not use ()
2212	 No type
2215	something wrong with [ and ]
2217	 No boundaries
2218	Dimension > 3
2219	No : (colon)
2220	 Boundary is not integer
2221	 Boundary is not integer
2222	Double description of the argument
2223	The name is used as a name of a variable
2224	The name is used as a name of a variable
2225	No arguments needed
2226	 No name - type is not needed
2227	Embedded (
2229	The variable is already declared
2230	Embedded [
2231	No right-hand boundary
2232	No value name
2233	 Boundary is not integer
2234	Extra boundary
2235	 No paired [
2236	No argument type 
2237	 No array boundaries
2238	No  [ here 
2239	 First alg cannot have any arguments
2240	Where is '(' ?
2241	No argument type 
2243	 Table cann't be returned
2244	 No do
2245	 No do 
2246	it's aLg or aRg
2247	"=" instead of  ":="
2301	No variable for assignment
2302	 No ]
2303	 ] before[
2304	Something after ]
2305	 Wrong brackets
2306	Unknown variable
2307	On the left-hand - const or arg 
2308	No indexes here
2309	No indexes
2310	 No right part
2311	Non integer index
2312	 Wrong number of indexes
2313	 different types on the right and left
2314	Comma in the end
2315	 On the left-hand - const or arg 
2384	Fragment not from a string
2401	No variable
2402	 Wrong name
2403	Unknown variable
2404	something wrong with [ and ]
2405	 Wrong name
2406	Unknown variable
2407	Wrong number of arguments
2408	Array name in the input list
2409	 lead const is impossible
2410	Error: not a condition
2411	Non integer index
2412	Comma in the end
2413	Array name in the input list
2414	symbols must to be leaded in one by one
2415	Error: not a variable
2416	Error: not a variable
2417	 No gap after lead
2418	argument value cann't be changed
2501	Extra  closing  bracket
2502	Extra opening  bracket
2503	Comma in the end
2504	What output? 
2505	Array name in the output list
2506	 No gap after derivation
2601	do: No key word
2602	No loop variable
2603	Loop variable is not descriped
2604	Value is necessary, not a const
2605	Not integer variable
2606	No "until"
2607	"to" in the wrong place
2608	From value is not integer
2609	"to" isn't iteger 
2610	"step" value  isn't integer
2611	How  many times?
2612	Something is after "times"
2613	"times" value is not integer
2614	Error: not bool
2615	 No condition for untill
2616	 from what?
2617	"step" isn't descriped
2618	 to what?
2619	"from" is missed
2701	Symbol in the name
2702	 No such algorithm
2703	Don't call alg-function 
2704	Wrong symbol in the name
2705	 No such algorithm
2706	Don't call alg-function 
2707	Extra  closing  bracket
2708	Extra opening  bracket
2709	No ) at the end
2710	Wrong parameter type
2711	Wrong usage
2712	 Wrong  type of variable
2713	No arguments
2714	Wrong dimension of the array 
2715	Not variable in res parameter
2716	Not variable in argres parameter
2717	Empty between brackets
2718	Wrong number of arguments
2719	empty argument
2720	Error in algorithm
2721	arg cann't be passed to res
2722	Needed name before (
2723	arg cann't be passed to argres
3101	No condition for assert
3102	No condition for assert
3103	 No condition for assert
3201	 No such alg
3202	Error: not a condition
3301	No such alg
3302	Error: not a condition
3401	No condition for "od_at" 
3402	No condition for "od_at" 
3403	No condition for "od_at" 
3404	Error: not a condition
3501	 No condition for if
3502	 No condition for if
3503	 No condition for if
3504	 Error in condition
3505	Error: not a condition
3601	No condition for cond
3602	No condition for cond
3603	No condition for cond
3604	Missed : at the end
3605	Error: not a condition
3701	Double description of the module
4101	Wrong exponentional form 
4102	Wrong exponentional form 
4103	Wrong exponentional form 
4104	Wrong exponentional form 
4105	Wrong exponentional form 
4106	Needed name before [
4107	"not" after name 
4108	Too many "not" in the name
4109	Wrong symbol in the name
4110	No such function
4111	"not" without bool
4112	Wrong symbol in the name
4113	Unknown variable or algorithm
4114	"not" without bool
4115	No arguments 
4116	"not" without bool
4117	Wrong symbol in the name
4118	Unknown variable
4119	Neither array, nor string
4120	Extra comma 
4121	Error: res with argres
4122	const not between (-2³¹...2³¹)
4123	const not between (-2¹⁰²³...2¹⁰²³)
4124	Too many " in the operand
4125	Operator is missed
4126	The algorithm does not return a value
4127	Error function
4128	This is not a function
4129	Wrong hexadecimal constant
4209	Error in the fragment description
4210	No ( 
4211	 ) instead of ]
4212	Empty between brackets
4213	 No [
4214	 ] instead of )
4215	Empty between brackets
4216	Extra comma 
4217	Extra comma 
4218	Empty between brackets
4219	 ) instead of ]
4220	No ':' here
4221	excess :
4222	excess :
4223	No boundary
4224	 No ]
4225	No ( 
4226	 No ]
4227	No ( 
4228	: instead of ,
4229	 , instead of :
4230	 ] instead of )
4301	Empty between brackets
4302	Error: only operation
4303	Neighbour operations
4304	Sign at the end of expression
4305	Empty between brackets
4306	Extra command
4307	Extra command
4308	Operation sign at the end of expression
4401	No indexes
4402	 Wrong number of indexes
4403	Non integer index
4404	No indexes
4405	Wrong number of indexes
4406	Non integer index
4407	Wrong number of arguments
4408	 Wrong  type of parameter
4409	Wrong usage of the res-parameter
4489	Плохие скобки
4490	Bad dimension
4491	Too complicated
4492	Not variable in res parameter
4493	arg cann't be passed to res
4494	arg cann't be passed to argres
4501	Bad operation
4502	Bad operation
4503	Bad operation
4504	Bad operation
4505	Bad operation
4506	Bad operation
4507	Bad operation
4508	Bad operation
4509	Bad operation
4510	Bad operation
4511	Error: int or int
4512	Error: int and int
4513	Error: int + int
4514	Error: int or real
4515	Error: int and real
4516	Error: int or real
4517	Error: int+bool
4518	Error: int-bool
4519	Error: int*bool
4520	Error: int/bool
4521	Error: int<bool
4522	Error: int>bool
4523	Error: int=bool
4524	Error: int**bool
4525	Error: int<>bool
4526	Error: int<=bool
4527	Error: int>=bool
4528	Error: int or bool
4529	Error: int + bool
4530	Error: int and bool
4531	Error: int+char
4532	Error: int-char
4533	Error: int*char
4534	Error: int/char
4535	Error: int<char
4536	Error: int>char
4537	Error: int=char
4538	Error: int**char
4539	Error: int<>char
4540	Error: int<=char
4541	Error: int>=char
4542	Error: int or char
4543	Error: int + char
4544	Error: int and char
4545	Error: int+string
4546	Error: int-string
4547	Error: int*string
4548	Error: int/string
4549	Error: int<string
4550	Error: int>string
4551	Error: int=string
4552	Error: int**string
4553	Error: int<>string
4554	Error: int<=string
4555	Error: int>=string
4556	Error: int or string
4557	Error: int + string
4558	Error: int and string
4559	Error: bool+bool
4560	Error: bool-bool
4561	Error: bool*bool
4562	Error: bool/bool
4563	Error: bool<bool
4564	Error: bool>bool
4565	Error: bool=bool
4566	Error: bool**bool
4567	Error: bool<>bool
4568	Error: bool<=bool
4569	Error: bool>=bool
4570	Error: bool or bool
4571	Error: bool + bool
4572	Error: bool and bool
4573	Error: bool+int
4574	Error: bool-int
4575	Error: bool*int
4576	Error: bool/int
4577	Error: bool<int
4578	Error: bool>int
4579	Error: bool=int
4580	Error: bool**int
4581	Error: bool<>int
4582	Error: bool<=int
4583	Error: bool>=int
4584	Error: bool or int
4586	Error: bool and int
4587	Error: bool+real
4588	Error: bool-real
4589	Error: bool*real
4591	Error: bool<real
4592	Error: bool>real
4593	Error: bool=real
4594	Error: bool**real
4595	Error: bool<>real
4596	Error: bool<=real
4597	Error: bool>=real
4598	Error: bool or real
5504	Error: not a condition
5601	Garbage after "select"
5602	Garbage after "then"
5603	Garbage after "else"
5604	Garbage after "end_if"
5605	Garbage after "end"
5606	Garbage after "end_do"
5607	Garbage after "begin"
5608	Garbage after "break"
5609	Garbage after "do"
6101	Wrong symbol in the name
6102	Digit at the beginnibg of the name
6103	Keyword inside the name
6104	Unpaired \"
6105	String in the name
7001	No Files module
7002	File does not exist
7003	File is already opened
7004	Cannot open "end_if"le
7005	File  is not opened
7006	End of "end_if"le
7007	File is read only
7008	File is write only
7009	Error in the "end_if"le
7010	Unknown key
7011	A key should be int
7012	Variables are not speci"end_if"ed
7014	A key should be int
7015	File is already exist
7016	Cannot create "end_if"le
7101	File was opened not as string
7102	File was opened not as int
7103	File was opened not as real
7104	File was opened not as char
7701	Embedded description of the function
8001	Zero division
8002	Unde"end_if"ned value
8003	Unknown algorithm
8004	Double description of the algorithm
8006	Too many descriptions
8007	Sintax error
8008	Bad description
8009	Wrong number of parameters
8010	Wrong parameter type
8011	No description
8012	Wrong name
8013	Wrong usage
8014	No expression
8015	Not corresponding types
8016	Impossible operation
8017	No index here
8018	Too complicated
8019	Wrong dimensi
8020	assrtion is false
8021	Below the lower bound of the array
8022	Below the lower bound of the array
8023	Below the lower bound of the array
8024	Out of array limits
8025	Out of array limits
8026	Many embedded functions
8027	Const in the input list
8028	Wrong input: Not integer
8029	Res parameter in the input list
8030	Wrong input: Not o number
8031	Wrong input: Should be "true" or "false" 
8032	Wrong input: More than one character
8033	Lower boundary greater than the upper one
8034	2nd index.: max less than min
8035	3rd index.: max less than min
8036	Плохое описание границ массива
8037	Index out of string
8038	Fragment out of string
8039	Unknown character
8040	Symbol is necessary, not a const
8041	Number of symbol < 1
8042	Wrong fragment boundaries
8043	Wrong dimension of the array 
8044	Integer overflow
8045	Negative power
8046	Wrong power for negative number
8047	Unde"end_if"ned element of array
8048	Real overflow
8049	Drawer error: wrong color
8050	False pre-condition
8051	False post-condition
8052	Square root of a negative number
8053	Impossible argument for arc
8061	Robot error: - it's a wall
8062	Robot error: environment is not ready
8101	Log of non-negative
8102	Log of non-negative
8103	2nd argument of  mod <= 0
8104	2nd argument of div <= 0
8105	No character
8106	Code is not from KOI8
11100	Bad info comment
11101	Line is out of algorithms
11102	Global variable after «alg»
11103	No break in the module
11104	No input from the module
11105	"pre" without "post"
12001	"if" not in algorithm
12002	"then" not in algorithm
12003	"end_if" not in algorithm
12004	"else" not in algorithm
12005	"select" not in algorithm
12006	"at" not in algorithm
12007	"od_at" not in algorithm
12008	"break" not in algorithm
12009	"do" not in algorithm
12010	"end_do" not in algorithm
12011	Line after module
12012	No "end_if" after "if"
12013	Should be after "begin"
12014	Embedded "begin"  
12015	"post" out of algorithm
12016	"pre" out of algorithm
12017	No algorithm header
12018	No "end_do"
12019	No "f"i after then
12020	 No "end_if" after "at"
12021	No "end_if" after select
12022	No "end_if" after else
12023	Нет то после если
12024	No  "'then" here
12025	No  "'begin" here
12026	No  "'at" here
20101	Where is the name?
20102	Where is the name?
20103	No boundaries here
20104	 No boundaries
20105	Dimension > 3
20106	Recursion in the boundary
20107	 Boundary is not integer
20108	 Boundary is not integer
20109	Recursion in the boundary
20110	Extra "res"
20111	Extra "arg"
20112	Extra "argres"
20113	Unpaired [
20114	Unpaired ]
20115	Bad boundary
20116	Bad boundary
20117	Bad boundary
20118	 , instead of :
20119	Double description
20202	No ) at the end
22351	Too many boundaries
45100	Error: bool and real
45101	Error: bool+char
45102	Error: bool-char
45103	Error: bool*char
45104	Error: bool/char
45105	Error: bool<char
45106	Error: bool>char
45107	Error: bool=char
45108	Error: bool**char
45109	Error: bool<>char
45110	Error: bool<=char
45111	Error: bool>=char
45112	Error: bool or char
45113	Error: bool + char
45114	Error: bool and char
45115	Error: bool+string
45116	Error: bool-string
45117	Error: bool*string
45118	Error: bool/string
45119	Error: bool<string
45120	Error: bool>string
45121	Error: bool=string
45122	Error: bool**string
45123	Error: bool<>string
45124	Error: bool<=string
45125	Error: bool>=string
45126	Error: bool or string
45127	Error: bool + string
45128	Error: bool and string
45129	Error: real or real
45130	Error: real + real
45131	Error: real and real
45132	Error: real or int
45133	Error: real + int
45134	Error: real and int
45135	Error: real + string
45136	Error: real - string
45137	Error: real * string
45138	Error: real / string
45139	Error: real < string
45140	Error: real > string
45141	Error: real = string
45142	Error: real ** string
45143	Error: real <> string
45144	Error: real <= string
45145	Error: real >= string
45146	Error: real or string
45147	Error: real + string
45148	Error: real and string
45149	Error: real + char
45150	Error: real - char
45151	Error: real * char
45152	Error: real / char
45153	Error: real < char
45154	Error: real > char
45155	Error: real = char
45156	Error: real ** char
45157	Error: real <> char
45158	Error: real <= char
45159	Error: real >= char
45160	Error: real or char
45161	Error: real + char
45162	Error: real and char
45163	Error: real + bool
45164	Error: real - bool
45165	Error: real * bool
45166	Error: real / bool
45167	Error: real < bool
45168	Error: real > bool
45169	Error: real = bool
45170	Error: real ** bool
45171	Error: real <> bool
45172	Error: real <= bool
45173	Error: real >= bool
45174	Error: real or bool
45175	Error: real + bool
45176	Error: real and bool
45177	Error: string-string
45178	Error: string*string
45179	Error: string/string
45180	Error: string**string
45181	Error: string or string
45182	Error: string + string
45183	Error: string and string
45184	Error: string-char
45185	Error: string*char
45186	Error: string/char
45187	Error: string**char
45188	Error: string or char
45189	Error: string + char
45190	Error: string and char
45191	Error: string+bool
45192	Error: string-bool
45193	Error: string*bool
45194	Error: string/bool
45195	Error: string<bool
45196	Error: string>bool
45197	Error: string=bool
45198	Error: string**bool
45199	Error: string<>bool
45200	Error: string<=bool
45201	Error: string>=bool
45202	Error: string or bool
45204	Error: string and bool
45205	Error: string+int
45206	Error: string-int
45207	Error: string*int
45208	Error: string/int
45209	Error: string<int
45210	Error: string>int
45211	Error: string=int
45212	Error: string**int
45213	Error: string<>int
45214	Error: string<=int
45215	Error: string>=int
45216	Error: string or int
45217	Error: string + int
45218	Error: string and int
45219	Error: string+real
45220	Error: string-real
45221	Error: string*real
45222	Error: string/real
45223	Error: string<real
45224	Error: string>real
45225	Error: string=real
45226	Error: string**real
45227	Error: string?real
45228	Error: string?real
45229	Error: string?real
45230	Error: string or real
45231	Error: string + real
45232	Error: string and real
45233	Error: char-string
45234	Error: char*string
45235	Error: char/string
45236	Error: char**string
45237	Error: char or string
45238	Error: char + string
45239	Error: char and string
45240	Error: char-char
45241	Error: char*char
45242	Error: char/char
45243	Error: char**char
45244	Error: char or char
45245	Error: char + char
45246	Error: char and char
45247	Error: char+bool
45248	Error: char-bool
45249	Error: char*bool
45250	Error: char/bool
45251	Error: char<bool
45252	Error: char>bool
45253	Error: char=bool
45254	Error: char**bool
45255	Error: char<>bool
45256	Error: char<=bool
45257	Error: char>=bool
45258	Error: char or bool
45259	Error: char + bool
45260	Error: char and bool
45261	Error: char+int
45262	Error: char-int
45263	Error: char*int
45264	Error: char/int
45265	Error: char<int
45266	Error: char>int
45267	Error: char=int
45268	Error: char**int
45269	Error: char<>int
45270	Error: char<=int
45271	Error: char>=int
45272	Error: char or int
45273	Error: char + int
45274	Error: char and int
45275	Error: char+real
45276	Error: char-real
45277	Error: char*real
45278	Error: char/real
45279	Error: char<real
45280	Error: char>real
45281	Error: char=real
45282	Error: char**real
45283	Error: char<>real
45284	Error: char<=real
45285	Error: char>=real
45286	Error: char or real
45287	Error: char + real
45288	Error: char and real
45289	Error: int and number comparison
45290	Error: int or number comparison
45291	Error: int + number comparison
45292	Error: int>string comparison
45293	Error: int<string comparison
45294	Error: int=string comparison
45295	Error: int<>string comparison
45296	Error: int>=string comparison
45297	Error: int<=string comparison
45298	Error: int and string comparison
45299	Error: int or string comparison
45300	Error: int + string comparison
45301	Error: real and bool
45302	Error: real or bool
45303	Error: real + bool
45304	Error: real > string comparison
45305	Error: real < string comparison
45306	Error: real = string comparison
45307	Error: real <> string comparison
45308	Error: real >= string comparison
45309	Error: real <= string comparison
45310	Error: real and string comparison
45311	Error: real or string comparison
45312	Error: real + string
45313	Error: number comparison and real
45314	Error: number comparison + real
45315	Error: number comparison or real
45316	Error: number comparison and int
45317	Error: number comparison + int
45318	Error: number comparison or int
45319	Error: number comparison+string
45320	Error: number comparison-string
45321	Error: number comparison*string
45322	Error: number comparison/string
45323	Error: number comparison<string
45324	Error: number comparison>string
45325	Error: number comparison=string
45326	Error: number comparison**string
45327	Error: number comparison<>string
45328	Error: number comparison<=string
45329	Error: number comparison>=string
45330	Error: number comparison or string
45331	Error: number comparison + string
45332	Error: number comparison and string
45333	Error: number comparison+char
45334	Error: number comparison-char
45335	Error: number comparison*char
45336	Error: number comparison/char
45337	Error: number comparison<char
45338	Error: number comparison>char
45339	Error: number comparison=char
45340	Error: number comparison**char
45341	Error: number comparison<>char
45342	Error: number comparison<=char
45343	Error: number comparison>=char
45344	Error: number comparison or char
45345	Error: number comparison + char
45346	Error: number comparison and char
45347	Error: number comparison<bool
45348	Error: number comparison>bool
45349	Error: number comparison=bool
45350	Error: number comparison<>bool
45351	Error: number comparison<=bool
45352	Error: number comparison>=bool
45353	Error: number comparison<string comparison
45354	Error: number comparison>string comparison
45355	Error: number comparison=string comparison
45356	Error: number comparison<>string comparison
45357	Error: number comparison>=string comparison
45358	Error: number comparison<=string comparison
45359	Error: number comparison>char
45360	Error: number comparison>string
45361	Error: number comparison>bool
45362	Error: string comparison<number comparison
45363	Error: string comparison>number comparison
45364	Error: string comparison=number comparison
45365	Error: string comparison<>number comparison
45367	Error: string comparison<=number comparison
45368	Error: string comparison>=number comparison
45369	Error: string comparison<bool
45370	Error: string comparison>bool
45371	Error: string comparison=bool
45372	Error: string comparison<>bool
45373	Error: string comparison<=bool
45374	Error: string comparison>=bool
45375	Error: string comparison or char
45376	Error: string comparison + char
45377	Error: string comparison and char
45378	Error: string comparison or string
45379	Error: string comparison + string
45380	Error: string comparison and string
45381	Error: string comparison+real
45382	Error: string comparison-real
45383	Error: string comparison*real
45384	Error: string comparison/real
45385	Error: string comparison<real
45386	Error: string comparison>real
45387	Error: string comparison=real
45388	Error: string comparison**real
45389	Error: string comparison<>real
45390	Error: string comparison<=real
45391	Error: string comparison>=real
45392	Error: string comparison or real
45393	Error: string comparison + real
45394	Error: string comparison and real
45395	Error: string comparison+int
45396	Error: string comparison-int
45397	Error: string comparison*int
45398	Error: string comparison/int
45399	Error: string comparison<int
45400	Error: string comparison>int
45401	Error: string comparison=int
45402	Error: string comparison**int
45403	Error: string comparison<>int
45404	Error: string comparison<=int
45405	Error: string comparison>=int
45406	Error: string comparison or int
45407	Error: string comparison + int
45408	Error: string comparison and int
45409	Error: char>string comparison
45410	Error: char>string comparison
45411	Error: char=string comparison
45412	Error: char<>string comparison
45413	Error: char>=string comparison
45414	Error: char<=string comparison
45415	Error: char or number comparison
45416	Error: char + string comparison
45417	Error: char and number comparison
45418	Error: char or string comparison
45419	Error: char + number comparison
45420	Error: char and string comparison
45421	Error: string>string comparison
45422	Error: string>string comparison
45423	Error: string=string comparison
45424	Error: string<>string comparison
45425	Error: string>=string comparison
45426	Error: string<=string comparison
45427	Error: string or number comparison
45428	Error: string + string comparison
45429	Error: string and number comparison
45430	Error: string or string comparison
45431	Error: string + number comparison
45432	Error: string and string comparison
45433	":=" instead of  "="
45490	Error: bool/real
112385	Error: int:=real
112386	Error: int:=char
112387	Error: int:=string
112388	Error: int:=bool
112389	Error: int:=int array
112390	Error: int:=real array
112391	Error: int:=char array
112392	Error: int:=string array
112393	Error: int:=bool array
112394	Error: real:= char
112395	Error: real:= string
112396	Error: real:= bool
112397	Error: real:= int array
112398	Error: real:= real array
112399	Error: real:= char array
201220	Double description
201221	Name conflict
201222	Wrong name
201223	":=" within the description
201224	Error: description ov "value"
201225	 No ]
1123100	Error: real:= string array
1123101	Error: real:= bool array
1123102	Error: char:=real
1123103	Error: char:=string
1123104	Error: char:=bool
1123105	Error: char:=int array
1123106	Error: char:=real array
1123107	Error: char:=char array
1123108	Error: char:=string array
1123109	Error: char:=bool array
1123110	Error: char:=int
1123111	Error: bool:=real
1123112	Error: bool:=char
1123113	Error: bool:=string
1123114	Error: bool:=int
1123115	Error: bool:=int array
1123116	Error: bool:=real array
1123117	Error: bool:=char array
1123118	Error: bool:=string array
1123119	Error: bool:=bool array
1123120	Error: string:=real
1123121	Error: string:=char
1123122	Error: string:=bool
1123123	Error: string:=int
1123124	Error: string:=int array
1123125	Error: string:=real array
1123126	Error: string:=char array
1123127	Error: string:=string array
1123128	Error: string:=bool array
1123129	The algorithm does not return a value
1123130	Error: assignment of function
1123131	Bad index
1123132	"value" out of function
1123133	Non integer index
1123134	Error: assignment to arg
1123135	No array name
1123136	No indexes of array
1123137	Error: assignment to array
11223138	Error: assignment to expression
11223140	Error: assignment to algorithm
11223141	Error: assignment to array
11223142	Error: assignment of array
2200001 Don't put "begin" in the module
2200008 "begin" inside the algorithm
2200009 "module" inside the algorithm
2200010 "end_module" inside the algorithm
2200101 No "begin" after "alg"
2200200 Line is in the wrong place
2200201 "end" is in the wrong place
2200205 "end_if" is in the wrong place
2200210 "end_do" is in the wrong place
2200211 "end_do_at" is in the wrong place
2200212 No algorithm implementation
2200214 "else" is in the wrong place
2200216 "pre" is in the wrong place
2200218 "switch" is in the wrong place
2200220 "if" is in the wrong place
2200603 Garbage inside "switch...case"
2200602 Garbage inside "if...then"
2200601 Garbage inside "alg...begin"
2200300 Unclosed construction
2200302 No paired "end_do"
2200304 No "then" for "if"
2200307 No "end_switch" after "switch...case"
2200308 No "end" for "begin"
2200309 Unclosed construction
2200401 No "case" after "switch"
2200404 No algorithm header
2200500 Line is out of the algorithm
2200504 "use" is not at the beginning
2200701 Condition is missed
2200801 Algorithm after the module
2200802 "if" is out of the algorithm
2200803 "switch" is out of the algorithm
2200804 Line after the algorithm
2200901	"use" is not at the beginning
2200902 Embedded algorithm
3000001 Impossible color
900001	No such module
