######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 11 13:07:06 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += kuznec.h network.h pult.h
SOURCES += kuznec.cpp main.cpp network.cpp pult.cpp
RESOURCES = application.qrc
TRANSLATIONS = rus.ts